/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package readwithus.MyFrame;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import readwithus.LHome;

/**
 *
 * @author Malindu
 */
public class CheckReserve extends javax.swing.JInternalFrame {
    DefaultTableModel dm = new DefaultTableModel();
String isbn,MID,LID, ReserveDate,ReserveDays,No_of_Book, Available,BorrowDate,DueDate,No_of_Day,Quntity;
    /**
     * Creates new form CheckReserve1
     */
    public CheckReserve() {
        initComponents();
        LoadTable ();
        LIDComb();
         Date date = new Date();
        jDateChooser2.setDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBorrowe = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtISBN = new javax.swing.JTextField();
        txtNoB = new javax.swing.JTextField();
        txtMID = new javax.swing.JTextField();
        LIDComb = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtstoke = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtNoDay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBorrowe.setBackground(new java.awt.Color(0, 153, 153));
        btnBorrowe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBorrowe.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrowe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/readwithus/images/BorrowButton.jpg"))); // NOI18N
        btnBorrowe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorroweActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrowe, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 130, 40));

        jButton5.setBackground(new java.awt.Color(0, 255, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/readwithus/images/BackButton.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 130, 40));

        jButton6.setBackground(new java.awt.Color(51, 51, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/readwithus/images/NewButton.jpg"))); // NOI18N
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 130, 40));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel1.setText("ISBN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setSelectionBackground(new java.awt.Color(51, 51, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 790, 120));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel3.setText("Member ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel4.setText("Reserve Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel7.setText("No of Books");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel8.setText("No of Days");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel12.setText("Available Books");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel13.setText("Librarian ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));
        jPanel1.add(txtISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 193, 29));
        jPanel1.add(txtNoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 193, 29));
        jPanel1.add(txtMID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 193, 29));

        LIDComb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ID" }));
        jPanel1.add(LIDComb, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 193, 29));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel5.setText("Borrowed Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jDateChooser2.setDateFormatString("MMM /d / yyyy");
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 193, 29));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel6.setText("Due Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        jDateChooser3.setDateFormatString("MMM /d / yyyy");
        jPanel1.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 193, 29));

        jLabel9.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel9.setText("Check Reserve Book");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        txtstoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstokeActionPerformed(evt);
            }
        });
        jPanel1.add(txtstoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 193, 29));

        jDateChooser1.setDateFormatString("MMM /d / yyyy");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 193, 29));
        jPanel1.add(txtNoDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 193, 29));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/readwithus/images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 950, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtstokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstokeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstokeActionPerformed

    private void btnBorroweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorroweActionPerformed
        isbn =  this.txtNoB.getText();
        MID =  this.txtMID.getText();
        LID =  this.LIDComb.getSelectedItem().toString();
        SimpleDateFormat Date = new SimpleDateFormat("yyyy-MM-dd");
        BorrowDate = Date.format(this.jDateChooser2.getDate());
        No_of_Book = this.txtNoB.getText();
        DueDate = Date.format(this.jDateChooser3.getDate());
        No_of_Day = this.txtNoDay.getText();
        Quntity = this.txtstoke.getText();
        DBConnect.DBconnect();
        try{
            Statement st = DBConnect.con.createStatement();
            st.executeUpdate("INSERT INTO `borrow` VALUES('"+isbn+"','"+MID+"','"+LID+"',"
                + "'"+BorrowDate+"','"+DueDate+"','"+No_of_Book+"','"+No_of_Day+"',null,null,null)");
            st.executeUpdate("UPDATE `book_purchase` SET `Quantity` = '"+Quntity+"' WHERE `ISBN`= '"+isbn+"'");
             st.executeUpdate("DELETE FROM `reserve` WHERE `MID`= '"+MID+" ");
            JOptionPane.showMessageDialog(null, "Book is Borrowed Successfully");

            DBConnect.con.close();
        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);

        }
    }//GEN-LAST:event_btnBorroweActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        LHome form = new LHome();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
void LoadTable ()
     {
         
         dm.addColumn("ISBN");
         dm.addColumn("MID");
         dm.addColumn("Reserve Date");
         dm.addColumn("No_of_Book");
         dm.addColumn("No_of_Date");
         String Query = "SELECT * FROM reserve ";
        DBConnect.DBconnect();
         try
         {
             Statement st = DBConnect.con.prepareStatement(Query);
             ResultSet rs = st.executeQuery(Query);
             while(rs.next()){
                isbn = rs.getString("ISBN");
                MID = rs.getString("MID");
                ReserveDate = rs.getString("Reserve_Date");
                No_of_Book = rs.getString("No_of_Book");
                No_of_Day = rs.getString("No_of_Days");
                 dm.addRow(new String[]{isbn, MID, ReserveDate, No_of_Book, No_of_Day});
             
            }
             this.jTable1.setModel(dm);
             
           DBConnect.con.close();
             
         
         }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
     }
  private void qty(){
 int stoke = Integer.parseInt(txtstoke.getText());
        int book = Integer.parseInt((String) txtNoB.getText()) ;
        if(stoke >=10   ){
            int Tot = ((stoke) - (book));
            String ava = String.valueOf(Tot);
            txtstoke.setText(ava);}
        else{
            JOptionPane.showMessageDialog(null, "Not Available Book");
        }
 }
  
   
    private void LIDComb()
    { 
         String Query = ("SELECT LID FROM librarian");
            DBConnect.DBconnect();
        try 
 
        {
             Statement st = DBConnect.con.prepareStatement(Query); 
             ResultSet rs = st.executeQuery(Query);
            while(rs.next())
            {      
               String ISBN=rs.getString("LID");
               LIDComb.addItem(ISBN);
            }
            
	 } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, ex);    
	 } 
        
}
     
    
    
  

   
 private void Date(){
     String ty = txtNoB.getText();
  String ss = txtNoB.getText();
 ty = "1";
 ss ="2";
        if(txtNoB.getText().equals(ss)){
         SimpleDateFormat dtf = new SimpleDateFormat("yyyy-MM-dd"); 
        String date2 = dtf.format(this.jDateChooser2.getDate());
        
        try
        {
          Date dates = dtf.parse(date2);
          Calendar cal = Calendar.getInstance();
          cal.add(Calendar.DAY_OF_MONTH, 14);
          Date futureDate = cal.getTime();
          String outD = dtf.format(futureDate);
          
       Date Adate = new SimpleDateFormat("yyyy-MM-dd").parse(outD); 
       this.jDateChooser3.setDate(Adate);
      
    }catch (java.text.ParseException pe)
    {
        JOptionPane.showMessageDialog(null, pe.getMessage());
    }
        
       
        } 
        else if (txtNoB.getText().equals(ty)){
         SimpleDateFormat dtf = new SimpleDateFormat("yyyy-MM-dd"); 
        String date2 = dtf.format(this.jDateChooser2.getDate());
        
        try
        {
          Date dates = dtf.parse(date2);
          Calendar cal = Calendar.getInstance();
          cal.add(Calendar.DAY_OF_MONTH, 7);
          Date futureDate = cal.getTime();
          String outD = dtf.format(futureDate);
          
       Date Adate = new SimpleDateFormat("yyyy-MM-dd").parse(outD); 
       this.jDateChooser3.setDate(Adate);
      
    }catch (java.text.ParseException pe)
    {
        JOptionPane.showMessageDialog(null, pe.getMessage());
    }
        }
        else
        {
        JOptionPane.showMessageDialog(null, "Please Select Item");
        }
     
 }
 
 

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     String query = "SELECT * FROM `reserve` ";
        DBConnect.DBconnect();
        try {

            Statement st = DBConnect.con.createStatement();
            ResultSet rs = st.executeQuery(query);
            while(rs.next()){
                txtISBN.setText(rs.getString("ISBN"));
                txtMID.setText(rs.getString("MID"));
                jDateChooser1.setDate(rs.getDate("Reserve_Date"));
                txtNoB.setText(rs.getString("No_of_Book"));
                txtNoDay.setText(rs.getString("No_of_Days"));
            }
            DBConnect.con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        String query1 = "SELECT Quantity FROM book_purchase";
        DBConnect.DBconnect();
        try {

            Statement st = DBConnect.con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            while(rs.next()){
                this.txtstoke.setText(rs.getString("Quantity"));

            }
            DBConnect.con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        Date();
        qty();
    }//GEN-LAST:event_jTable1MouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox LIDComb;
    private javax.swing.JButton btnBorrowe;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtISBN;
    private javax.swing.JTextField txtMID;
    private javax.swing.JTextField txtNoB;
    private javax.swing.JTextField txtNoDay;
    private javax.swing.JTextField txtstoke;
    // End of variables declaration//GEN-END:variables

    private void deplace(int[] i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
