/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package readwithus.MyFrame;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Malindu
 */
public class CheckOverDue extends javax.swing.JInternalFrame {

  String isbn,MID,LID,No_of_Book,BorrowDate,DueDate,No_of_Day,Return_Date;
    /**
     * Creates new form CheckOverDue
     */
    public CheckOverDue() {
        initComponents();
        LoadTable ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "ddfbf"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 810, 260));

        jLabel9.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel9.setText("OverDue");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/readwithus/images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -56, 930, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-11, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
void LoadTable ()
     { DefaultTableModel dm = new DefaultTableModel();
         dm.addColumn("MID");  
         dm.addColumn("ISBN");
         dm.addColumn("Borrowe Date");
         dm.addColumn("Due Date");
         dm.addColumn("No_of_Book");
         dm.addColumn("No_of_Days");
         dm.addColumn("Return_Date");
         String Query = "SELECT * FROM Borrow WHERE Due_Date < Return_Date ";
        DBConnect.DBconnect();
         try
         {
             Statement st = DBConnect.con.prepareStatement(Query);
             ResultSet rs = st.executeQuery(Query);
             while(rs.next()){
                MID = rs.getString("MID"); 
                isbn = rs.getString("ISBN");
                BorrowDate = rs.getString("Borrow_Date");
                DueDate = rs.getString("Due_Date");
                No_of_Book = rs.getString("No_of_Book");
                No_of_Day = rs.getString("No_of_Days");
                Return_Date = rs.getString("Return_Date");
                 dm.addRow(new String[]{ MID,isbn, BorrowDate,DueDate, No_of_Book, No_of_Day,Return_Date});
            }
             this.jTable1.setModel(dm);
           DBConnect.con.close();
         }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
