/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package readwithus.MyFrame;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import readwithus.LHome;
/**
 *
 * @author Malindu
 */
public class Librarian extends javax.swing.JFrame {
        String LID,Fname, Lname,NIC, AdL1,AdL2,dob,username, password, contact1, contact2;
       
        
        

    /**
     * Creates new form InsertLibrarian
     */
    public Librarian() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtADL2 = new javax.swing.JTextField();
        txtADL1 = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        txtContact2 = new javax.swing.JTextField();
        txtContact1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtFName = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtADL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 193, 29));
        jPanel1.add(txtADL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 193, 29));
        jPanel1.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 193, 29));

        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKeyPressed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 193, 29));
        jPanel1.add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 193, 29));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel1.setText("Date of Birth");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel4.setText("Librarian ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel6.setText("First Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel5.setText("NIC no");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel7.setText("Address line 2");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel12.setText("Address line 1");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel9.setText("username");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel10.setText("Password");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, -1, -1));

        jCheckBox1.setText("Show Passowrd");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 560, -1, 29));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 193, 29));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 193, 29));
        jPanel1.add(txtContact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 193, 29));
        jPanel1.add(txtContact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 193, 29));

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel13.setText("Alt. Contact No");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel8.setText("Contact No");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));

        btnDelete.setBackground(new java.awt.Color(239, 33, 33));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 161, 50));

        btnUpdate.setBackground(new java.awt.Color(204, 102, 0));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 161, 50));

        btnBack.setBackground(new java.awt.Color(0, 255, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 161, 50));

        btnClear.setBackground(new java.awt.Color(51, 51, 255));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("New");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 161, 50));

        btnSave.setBackground(new java.awt.Color(51, 153, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 161, 50));
        jPanel1.add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 193, 29));

        jDateChooser1.setDateFormatString("MMM /d / yyyy");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 193, 29));

        jLabel11.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel11.setText("Librarian Details");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/readwithus/images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        LHome form = new LHome();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(this.txtID.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(null, "Please Insert ID");
        }
        else if (this.txtFName.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(null,  "Please Insert First Name");
        }
        else if (this.txtLName.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(null,  "Please Insert Last Name");
        }
        else if (this.jDateChooser1.getDate()== null)
        {
            JOptionPane.showMessageDialog(null,  "Please Choose Date of Birth");
        }
        else if (this.txtNIC.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(null,  "Please Insert NIC Number");
        }
         else if (this.txtADL1.getText().isEmpty()==true || this.txtADL2.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(null,  "Please Insert Addrees");
        }
          else if (this.txtContact1.getText().isEmpty()==true && this.txtContact2.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(null,  "Please Insert one or more Contact No");
        }
        else if (this.txtUsername.getText().isEmpty()==true)
        {
            JOptionPane.showMessageDialog(null,  "Please Insert Username");
        }
         else if (this.txtPassword.getPassword().length ==0)
        {
            JOptionPane.showMessageDialog(null,  "Please Insert Password");
        }
        else
         {
             
            String regex = "^\\+?[0-9.()-]{10,25}$";
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(contact1 );
             Matcher matcher1 = pattern.matcher(contact1 );
             if(matcher.matches() && matcher1.matches())
             {
            LID = this.txtID.getText();
            Fname = this.txtFName.getText();
            Lname = this.txtLName.getText();
            NIC = this.txtNIC.getText();
            AdL1 = this.txtADL1.getText();
            AdL2 = this.txtADL2.getText();
            SimpleDateFormat Date = new SimpleDateFormat("yyyy-MM-dd");
            dob = Date.format(this.jDateChooser1.getDate());
             username = this.txtUsername.getText();
            contact1 =this.txtContact1.getText();
            contact2 =this.txtContact2.getText();
            password = String.valueOf((this.txtPassword.getPassword()));
            DBConnect.DBconnect();
            try{
                
                Statement st = DBConnect.con.createStatement();
                st.executeUpdate("INSERT INTO `librarian` VALUES('"+LID+"','"+Fname+"','"+Lname+"',"
                        + "'"+NIC+"','"+AdL1+"','"+AdL2+"','"+dob+"','"+username+"','"+password+"')");
                st.executeUpdate("INSERT INTO `librarian_contact` VALUES('"+LID+"','"+contact1+"','"+contact2+"')");
                JOptionPane.showMessageDialog(null, "Data Insert Successfully");
                 ClearData();
                DBConnect.con.close();
            }catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex);
            
            }
         
             }
         }
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

  
    
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
            LID = this.txtID.getText();
            Fname = this.txtFName.getText();
            Lname = this.txtLName.getText();
            SimpleDateFormat Date = new SimpleDateFormat("yyyy-MM-dd");
            dob = Date.format(this.jDateChooser1.getDate());
            NIC = this.txtNIC.getText();
            AdL1 = this.txtADL1.getText();
            AdL2 = this.txtADL2.getText();
            contact1 =this.txtContact1.getText();
            contact2 =this.txtContact2.getText();
            username = this.txtUsername.getText();
            password = String.valueOf(this.txtPassword.getPassword());
           
            DBConnect.DBconnect();
        
        try{
            Statement st = DBConnect.con.createStatement();
            st.executeUpdate("UPDATE `librarian` SET `FirstName`='"+Fname+"',`LastName`='"+Lname+"',"
                    + "`DOB`="+dob+",`NIC`="+NIC+",`AddressL1`='"+AdL1+"',`AddressL2`='"+AdL2+"',"
                    + "`UserName`='"+username+"',`password`='"+password+"', `ContactNo1` ='"+contact1+"',"
                    + "`ContactNo1` ='"+contact2+"' WHERE `LID`= '"+LID+"' ");
            JOptionPane.showMessageDialog(null, "Data Updated Successfully");
            ClearData();
            DBConnect.con.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        ClearData();
    }//GEN-LAST:event_btnClearActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       if(jCheckBox1.isSelected())
       {
           txtPassword.setEchoChar((char)0);
       }else
       {
          txtPassword.setEchoChar('*'); 
       }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         LID = this.txtID.getText();
        DBConnect.DBconnect();

        try{
            Statement st = DBConnect.con.createStatement();
            st.executeUpdate("DELETE FROM `librarian` WHERE `LID`= '"+LID+"' ");
            JOptionPane.showMessageDialog(null, "Data Deleted Successfully");
            ClearData();
            DBConnect.con.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyPressed
         if(evt.getKeyCode()== KeyEvent.VK_ENTER){
        LID = this.txtID.getText();
        String Query = "SELECT * ,ContactNo1, ContactNo2 FROM librarian INNER JOIN librarian_contact ON librarian.LID = librarian_contact.LID WHERE librarian.LID = '"+LID+"' ";
        DBConnect.DBconnect();
        
        try
        {
            Statement st = DBConnect.con.createStatement();
            ResultSet rs = st.executeQuery(Query);
            while(rs.next()){
                this.txtFName.setText(rs.getString("FirstName"));
                this.txtLName.setText(rs.getString("LastName"));
                this.txtNIC.setText(rs.getString("NIC"));
                this.txtADL1.setText(rs.getString("AddressL1"));
                this.txtADL2.setText(rs.getString("AddressL2"));
                this.jDateChooser1.setDate(rs.getDate("DOB"));
                this.txtUsername.setText(rs.getString("username"));
                this.txtPassword.setText(rs.getString("password"));
                this.txtContact1.setText(rs.getString("ContactNo1"));
                this.txtContact2.setText(rs.getString("ContactNo2"));
                
             
            }
           DBConnect.con.close();
        
        }  catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
                    }
          }
    }//GEN-LAST:event_txtIDKeyPressed
      void ClearData(){
        this.txtID.setText("");
        this.txtFName.setText("");
        this.txtLName.setText("");
        this.jDateChooser1.setDate(null);
        this.txtNIC.setText("");
        this.txtADL1.setText("");
        this.txtADL2.setText("");
        this.txtUsername.setText("");
        this.txtPassword.setText("");
        txtContact1.setText("");
        txtContact2.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Librarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Librarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox jCheckBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtADL1;
    private javax.swing.JTextField txtADL2;
    private javax.swing.JTextField txtContact1;
    private javax.swing.JTextField txtContact2;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
