/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package readwithus.MyFrame;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import readwithus.LHome;

/**
 *
 * @author Malindu
 */
public class Reserve extends javax.swing.JInternalFrame {
 String isbn,MID, ReserveDate,ReserveDays,No_of_Book, Available,No_of_Day,Quntity;
    /**
     * Creates new form Reserve1
     */
    public Reserve() {
        initComponents();
        MIDComb();
        ISBNComb();
        
        Date date = new Date();
        jDateChooser1.setDate(date);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ISBNComb = new javax.swing.JComboBox();
        MIDComb = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        NOBCombo = new javax.swing.JComboBox();
        txtstoke = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtNoDay = new javax.swing.JTextField();
        btnReserve = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel1.setText("ISBN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        ISBNComb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ISBN" }));
        jPanel1.add(ISBNComb, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 193, 29));

        MIDComb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ID" }));
        MIDComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIDCombActionPerformed(evt);
            }
        });
        jPanel1.add(MIDComb, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 193, 29));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel3.setText("Member ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel4.setText("Reserve Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel7.setText("No of Books");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, 20));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel8.setText("No of Days");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, 20));

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel12.setText("Available Books");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, 20));

        jLabel9.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel9.setText("Reserve Book");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        NOBCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1", "2" }));
        NOBCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOBComboActionPerformed(evt);
            }
        });
        jPanel1.add(NOBCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 193, 30));

        txtstoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstokeActionPerformed(evt);
            }
        });
        jPanel1.add(txtstoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 193, 30));

        jDateChooser1.setDateFormatString("MMM /d / yyyy");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 193, 29));
        jPanel1.add(txtNoDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 193, 30));

        btnReserve.setBackground(new java.awt.Color(255, 153, 102));
        btnReserve.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReserve.setForeground(new java.awt.Color(255, 255, 255));
        btnReserve.setText("Reserve");
        btnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveActionPerformed(evt);
            }
        });
        jPanel1.add(btnReserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 161, 50));

        jButton5.setBackground(new java.awt.Color(0, 255, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 161, 50));

        jButton6.setBackground(new java.awt.Color(51, 51, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("New");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 161, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/readwithus/images/background.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -56, 930, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 930, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MIDCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIDCombActionPerformed

    }//GEN-LAST:event_MIDCombActionPerformed

    private void NOBComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOBComboActionPerformed

        NOD();
        qty();
    }//GEN-LAST:event_NOBComboActionPerformed

    private void txtstokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstokeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstokeActionPerformed

    private void btnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveActionPerformed
        if( this.ISBNComb.getSelectedItem().equals("SELECT ISBN"))
        {
            JOptionPane.showMessageDialog(null,  "Please Select ISBN ");
        }
        else if (this.MIDComb.getSelectedItem().equals("SELECT ID"))
        {
            JOptionPane.showMessageDialog(null,  "Please Select Member ID");
        }
        else if (this.NOBCombo.getSelectedItem().equals("Select"))
        {
            JOptionPane.showMessageDialog(null,  "Please Insert Number of Book");
        }
        else
        {
            isbn = ISBNComb.getSelectedItem().toString();
            MID  = MIDComb.getSelectedItem().toString();
            ReserveDays = txtNoDay.getText();
            No_of_Book =  NOBCombo.getSelectedItem().toString();
            SimpleDateFormat Date = new SimpleDateFormat("yyyy-MM-dd");
            ReserveDate = Date.format(this.jDateChooser1.getDate());
            DBConnect.DBconnect();
            try{
                Statement st = DBConnect.con.createStatement();
                st.executeUpdate("INSERT INTO `reserve` VALUES('"+isbn+"','"+MID+"','"+ReserveDate+"',"
                    + "'"+No_of_Book+"','"+ReserveDays+"')");
                JOptionPane.showMessageDialog(null, "Book Reserved Successfully");
                DBConnect.con.close();
            }catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex);

            }

        }
    }//GEN-LAST:event_btnReserveActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        LHome form = new LHome();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

   
    
    
       private void ISBNComb()
    { 
         String Query = ("SELECT * FROM book");
            DBConnect.DBconnect();
        try 
 
        {  
           
             Statement st = DBConnect.con.prepareStatement(Query); 
             ResultSet rs = st.executeQuery(Query);
            while(rs.next())
            {      
               String ISBN=rs.getString("ISBN");
               ISBNComb.addItem(ISBN);
               
            }
            
	 } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, ex);    
	 } 
        
}
      private void MIDComb()
    { 
        try 
 
        {  
            String Query = ("SELECT * FROM reserve;");
            DBConnect.DBconnect();
            Statement st = DBConnect.con.prepareStatement(Query); 
            ResultSet rs = st.executeQuery(Query);
            while(rs.next())
            {      
               MID=rs.getString("MID");
               MIDComb.addItem(MID); 
            }
         
	 } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, ex);    
	 }      
}
    
      
       private void NOD(){
     String ty = NOBCombo.getSelectedItem().toString();
     String ss = NOBCombo.getSelectedItem().toString();
     ty = "1";
     ss ="2";
       if(NOBCombo.getSelectedItem().equals(ty)){
       txtNoDay.setText("7");
       }
        else if (NOBCombo.getSelectedItem().equals(ss)){
         txtNoDay.setText("14");
        }
       else
        {
        JOptionPane.showMessageDialog(null, "Please Select Item");
        }
       }
       
       
     
    
   private void qty(){
 int stoke = Integer.parseInt(txtstoke.getText());
        int book = Integer.parseInt((String) NOBCombo.getSelectedItem()) ;
        if(stoke >=10   ){
            int Tot = ((stoke) - (book));
            String ava = String.valueOf(Tot);
            txtstoke.setText(ava);}
        else{
            JOptionPane.showMessageDialog(null, "Not Available Book");
        }
 }   
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ISBNComb;
    private javax.swing.JComboBox MIDComb;
    private javax.swing.JComboBox NOBCombo;
    private javax.swing.JButton btnReserve;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNoDay;
    private javax.swing.JTextField txtstoke;
    // End of variables declaration//GEN-END:variables
}
