/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package readwithus.MyFrame;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import readwithus.LHome;

/**
 *
 * @author Malindu
 */
public class Return extends javax.swing.JFrame {
              String isbn,MID,LID, BorrowDate,ReturnDate, DueDate,No_of_Day,No_of_Book,Quntity,Fine, Amount;
    /**
     * Creates new form Return
     */
    public Return() {
        initComponents();
         ISBNComb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDay = new javax.swing.JTextField();
        txtFine = new javax.swing.JTextField();
        ISBNComb = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtTotFine = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtstoke = new javax.swing.JTextField();
        txtMID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnReturn = new javax.swing.JButton();
        txtNOB = new javax.swing.JTextField();
        txtLID = new javax.swing.JTextField();
        txtCharge = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        txtNoDay = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel1.setText("ISBN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel16.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel16.setText("Day");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        txtDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDayMouseClicked(evt);
            }
        });
        jPanel1.add(txtDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 193, 29));
        jPanel1.add(txtFine, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 193, 29));

        ISBNComb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT ISBN" }));
        ISBNComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISBNCombActionPerformed(evt);
            }
        });
        jPanel1.add(ISBNComb, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 193, 29));

        jLabel17.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel17.setText("Fine RS :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        jLabel18.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel18.setText("Total Fine  RS :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));
        jPanel1.add(txtTotFine, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 193, 29));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel3.setText("Member ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel4.setText("Borrowed Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel5.setText("Return Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel6.setText("Due Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel7.setText("No of Books");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel8.setText("No of Days");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel12.setText("Available Books");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));
        jPanel1.add(txtstoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 193, 29));
        jPanel1.add(txtMID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 193, 29));

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel11.setText("Charge Cost RS :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 130, -1));

        btnReturn.setBackground(new java.awt.Color(204, 102, 0));
        btnReturn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/readwithus/images/ReturnButton.jpg"))); // NOI18N
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 130, 40));
        jPanel1.add(txtNOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 193, 29));
        jPanel1.add(txtLID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 193, 29));

        txtCharge.setText("5");
        txtCharge.setName(""); // NOI18N
        jPanel1.add(txtCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 193, 29));

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        jLabel13.setText("Librarian ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Footlight MT Light", 1, 36)); // NOI18N
        jLabel9.setText("Return Book");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jDateChooser3.setDateFormatString("MMM /d / yyyy");
        jPanel1.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 193, 29));

        jDateChooser1.setDateFormatString("MMM /d / yyyy");
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 193, 29));

        jDateChooser2.setDateFormatString("MMM /d / yyyy");
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 193, 29));
        jPanel1.add(txtNoDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 193, 29));

        jButton5.setBackground(new java.awt.Color(0, 255, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/readwithus/images/BackButton.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 130, 40));

        btnNew.setBackground(new java.awt.Color(51, 51, 255));
        btnNew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNew.setForeground(new java.awt.Color(255, 255, 255));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/readwithus/images/NewButton.jpg"))); // NOI18N
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/readwithus/images/background.jpg"))); // NOI18N
        jLabel2.setName("5"); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 980, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDayMouseClicked
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(this.jDateChooser2.getDate());

        SimpleDateFormat dtf = new SimpleDateFormat("yyyy-MM-dd");
        String date2 = dtf.format(this.jDateChooser3.getDate());

        try
        {
            java.util.Date d1 = sdf. parse (date);
            java.util.Date d2 = dtf. parse (date2);

            long days = (d1.getTime()- d2.getTime())/(24*60*60*1000);
           if(days>=1){
            txtDay.setText(""+days);
            fine();}
           else
           {
               JOptionPane.showMessageDialog(null,"ON Time Return Book, No Fine Charges");
               txtDay.setText("0");
               fine();
           }
        }catch (java.text.ParseException pe)
        {
            JOptionPane.showMessageDialog(null, pe.getMessage());
        }
    }//GEN-LAST:event_txtDayMouseClicked

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        if (this.jDateChooser2.getDate()== null)
        {
            JOptionPane.showMessageDialog(null,  "Please Choose Return Date ");
        }
        else
        {
            SimpleDateFormat Date = new SimpleDateFormat("yyyy-MM-dd");
            ReturnDate = Date.format(this.jDateChooser2.getDate());
            Fine  = this.txtFine.getText();
            Amount =this.txtTotFine.getText();
            DBConnect.DBconnect();
            try{
                Statement st = DBConnect.con.createStatement();
                st.executeUpdate("UPDATE `borrow` SET `Return_Date`= '"+ReturnDate+"',`Fine`='"+Fine+"',"
                        + "`Amount`='"+Amount+"' WHERE `ISBN` = '"+isbn+"'");
                returnBook();
                JOptionPane.showMessageDialog(null, "Book Returned");
                clear();
                DBConnect.con.close();
            }catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex);

            }

        }
    }//GEN-LAST:event_btnReturnActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        LHome form = new LHome();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ISBNCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISBNCombActionPerformed
        isbn = this.ISBNComb.getSelectedItem().toString();

        String Query = "SELECT * FROM borrow  WHERE ISBN = '"+isbn+"' ";

        DBConnect.DBconnect();

        try
        {
            Statement st = DBConnect.con.createStatement();
            ResultSet rs = st.executeQuery(Query);
            while(rs.next()){
               
                txtMID.setText(rs.getString("MID"));
                txtLID.setText(rs.getString("LID"));
                jDateChooser1.setDate(rs.getDate("Borrow_Date"));
                jDateChooser3.setDate(rs.getDate("Due_Date"));
                txtNOB.setText(rs.getString("No_of_Book"));
                txtNoDay.setText(rs.getString("No_of_Days"));

            }
            borrow();
            DBConnect.con.close();

        }  catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
       
    }//GEN-LAST:event_ISBNCombActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
       clear();
    }//GEN-LAST:event_btnNewActionPerformed
  void clear(){
        ISBNComb.setSelectedItem("SELECT ISBN");
        txtMID.setText("");
        txtLID.setText("");
        txtNOB.setText(" ");
        jDateChooser1.setDate(null);
        jDateChooser3.setDate(null);
        txtNoDay.setText("");
        txtstoke.setText("");
        txtNoDay.setText("");
        txtstoke.setText("");
        jDateChooser2.setDate(null);
        txtDay.setText("");
        txtFine.setText("");
        txtTotFine.setText("");
 }
    
    private void returnBook(){
        int stoke = Integer.parseInt(txtstoke.getText());
        int book = Integer.parseInt(txtNOB.getText()) ;
       
            int Tot = ((stoke) + (book));
            String ava = String.valueOf(Tot);
            txtstoke.setText(ava);
            
            Quntity = this.txtstoke.getText();
            DBConnect.DBconnect();
            try{
                Statement st = DBConnect.con.createStatement();
                st.executeUpdate("UPDATE `book_purchase` SET `Quantity` = '"+Quntity+"' WHERE `ISBN`= '"+isbn+"'");

                DBConnect.con.close();
            }catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex);

            }
 }
    
   
    void borrow() {
       isbn = ISBNComb.getSelectedItem().toString();
        String query = "SELECT * FROM book_purchase WHERE ISBN='" + isbn + "' ;";
        try {
            
            Statement st = DBConnect.con.createStatement();
            ResultSet rs = st.executeQuery(query);
            while(rs.next()){
             this.txtstoke.setText(rs.getString("Quantity"));

            }
             DBConnect.con.close();
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, ex); 
        }
    }
    
    private void fine(){
                double day = Double.parseDouble(txtDay.getText());
               
                double charge  = Double.parseDouble(txtCharge.getText());
                double books =  Double.parseDouble(txtNOB.getText());
                day =  Double.parseDouble(txtDay.getText());
                double fine = charge * day;
                 String fi = String.valueOf(fine);
                txtFine.setText(fi);
                double ToT = Double.parseDouble(txtFine.getText());
                double Total = ToT* books;
                String tot = String.valueOf(Total);
                txtTotFine.setText(tot);
    }
     private void ISBNComb()
    { 
         String Query = ("SELECT * FROM borrow");
            DBConnect.DBconnect();
        try 
 
        {  
             Statement st = DBConnect.con.prepareStatement(Query); 
             ResultSet rs = st.executeQuery(Query);
            while(rs.next())
            {      
               String ISBN=rs.getString("ISBN");
               ISBNComb.addItem(ISBN);
               
            }
            
	 } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, ex);    
	 } 
        
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Return.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Return().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ISBNComb;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCharge;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtFine;
    private javax.swing.JTextField txtLID;
    private javax.swing.JTextField txtMID;
    private javax.swing.JTextField txtNOB;
    private javax.swing.JTextField txtNoDay;
    private javax.swing.JTextField txtTotFine;
    private javax.swing.JTextField txtstoke;
    // End of variables declaration//GEN-END:variables
}
